services:
 db:
  image: postgres:latest
  ports:
   - 5432:5432
  environment:
   POSTGRES_DATABASE: word-cloud-db
   POSTGRES_USERNAME: postgres
   POSTGRES_PASSWORD: password
  volumes:
   - ./db:/var/lib/postgresql/data
   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
 frontend:
  build:
   dockerfile: ./Dockerfile
   context: ../word-cloud-frontend
  ports:
   - 3000:3000
 worker:
  build:
   dockerfile: ./Dockerfile
   context: ../word-cloud-worker
  ports:
   - 8080:8080
  links:
   - db
  environment:
   - MYAPP_JDBC_URL=jdbc:postgresql://db/word-cloud-db
   - RABBIT_HOST=mq
  depends_on:
   - db
 mq:
  image: rabbitmq:management
  ports:
   - 5672:5672
   - 15672:15672
  environment:
   RABBIT_DEFAULT_USER: guest
   RABBIT_DEFAULT_PASSWORD: guest
 core:
  build:
   dockerfile: ./Dockerfile
   context: ../word-cloud-core
  ports:
   - 8081:8080
  links:
   - db
  environment:
   - MYAPP_JDBC_URL=jdbc:postgresql://db/word-cloud-db
   - RABBIT_HOST=mq
  depends_on:
   - db
